### ISSUE TITLE
is this cookbook tested for chef 12?

### ISSUE THREAD

**Issue by baryonicdm** [chef-brigade/dhcp-cook#44]
readme file indicates that chef 10+ will be compatible. is there anybody who tried this cookbook for chef 12?

**Comment by jmccann** [comment]
I tried just now and it doesn't seem to work properly.  One issue I ran into is it does not update the list.conf files properly to include all the other generated sub config files.

This is do to the following methods in each provider not seeming to work properly anymore: https://github.com/spheromak/dhcp-cook/blob/master/providers/subnet.rb#L3-L24

**Comment by spheromak** [comment]
@jmccann I have moved this cookbook into the chef-brigade. If you or anyone else is interested in maintaining it you can join the brigade.

**Comment by jmccann** [comment]
@spheromak Awesome.  How do I now join the brigade? :smile:
